### ISSUE TITLE
--kubeconfig for tkn versionn

### ISSUE THREAD

**Issue by didier-durand** [tektoncd/cli#1212]
Hi there,
"tkn version" does not allow the --kubeconfig parameter as other tkn command do.

For example, with Microk8s on my Mac, I would like to be able to specify --kubeconfig to route the version check of pippeline component to the K8s-hosting VM installed by MicroK8s

Currently, I get this the following:

_"Client version: 0.13.0
Pipeline version: unknown, pipeline controller may be installed in another namespace please use tkn version -n {namespace}"_

Thanks 

didier

**Comment by danielhelfand** [comment]
Sure, it makes sense to add `--kubeconfig` to `tkn version`. There is a slight conflict that we may need to work out though. Since version features a `--check` option with the shorthand `-c`, it conflicts with another flag that is part of the global flags every command except version has.

The global flags include `--context`, which also has a `-c` shorthand, so we would need to work out how to properly deprecate this for `--check`. Then the option could be added.

**Comment by didier-durand** [comment]
@danielhelfand : thanks for the quick feedback and the details! I'll be happy to be among the first testers when ready: just ping me when you pushed it. Best, Didier

**Comment by kobayashi** [comment]
How about just remove shorthand flag `-c` to check version and just add `--check`?

**Comment by didier-durand** [comment]
@danielhelfand : I didn't find in kubectl doc that -c is the "official" shorthand for --kubeconfig. Can you point me to your reference? Anyway, it's for me fine to start with --kubeconfig and provide a shorthand like your proposed -c (or else) later on. 
Didier

**Comment by danielhelfand** [comment]
The `-c` shorthand is not for `--kubeconfig`. It's for `--check` and `--context`. `--check` is a flag for `tkn version`:

```
tkn version -h
Prints version information

Usage:
tkn version [flags]

Flags:
  -c, --check              check if a newer version is available
  -h, --help               help for version
  -n, --namespace string   namespace to check installed controller version
```

`--context` is a global flag available with most commands with the exception of `tkn version` and `tkn completion`:

```
tkn pipeline ls -h
Lists Pipelines in a namespace

Usage:
tkn pipeline list [flags]

Aliases:
 ...

Flags:
  ...

Global Flags:
  -c, --context string      name of the kubeconfig context to use (default: kubectl config current-context)
``` 

If we add the global flags to `tkn version`, there will be a conflict as flags can't have the same shorthand. 

Additionally, we cannot just remove `-c` since it may break people who are using the shorthand. We need to give a notice before removing the shorthand so people are prepared.

**Comment by didier-durand** [comment]
@danielhelfand : yes, that's my point. SInce -c is not a shorthand for --kubeconfig, it seems to me that you don't have to change anything regarding -c for the time being. All what's needed at this point is this addition of --kubeconfig to match kubectl, istioctl, etc.

**Comment by danielhelfand** [comment]
As discussed in our working group today, the plan is to add all global options to `tkn version` by v0.15.0 and add a deprecation notice for `-c` with `--check` as part of the upcoming release. 

Additionally, I will explore further on what approach we can do to conditionally add global flags so that `--kubeconfig` can be added as part of v0.14.0.

**Comment by didier-durand** [comment]
Excellent! Thanks. 
Didier

**Comment by didier-durand** [comment]
@danielhelfand : good news! Thanks for the corresponding work. Didier
