### ISSUE TITLE
Remove PipelineResource support and subcommands

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/cli#1657]
/kind cleanup 

PipelineResource is deprecated and is removed with the removal of v1alpha1, we need to remove it from `tkn`.

/assign

**Comment by vdemeester** [comment]
Actually, it is still there, so it's less of a priority than I though.

**Comment by AlanGreene** [comment]
I was a little worried when I saw this since the Dashboard still relies on PipelineResource support for its import functionality and I thought I had missed something in the recent Pipeline release notes 😅  Looks like it was only the v1alpha1 versions of the v1beta1 resources that were removed so we're OK for now… 😌

**Comment by vdemeester** [comment]
@AlanGreene yeah, I got confused by my own change ; long back I moved the PipelineResource go type to their own package, so when I looked this morning I was like "oh PipelineResource is gone from `v1alpha1`".. but ain't true 😹. It's just in a different package 🙃

**Comment by pradeepitm12** [comment]
For the time being we can add deprecation flag/message for the pipelineresource command.

**Comment by piyush-garg** [comment]
We have marked them deprecated some release ago, waiting for them to be removed in pipeline, we will do the same along with that

**Comment by JeromeJu** [comment]
Thank you for taking the precautions here!

Since the  `pipelineResources` are going to be removed in pipeline _v0.45_  as designed in [TEP074](https://github.com/tektoncd/community/blob/main/teps/0074-deprecate-pipelineresources.md) and according to [deprecation.md](https://github.com/tektoncd/pipeline/blob/main/docs/deprecations.md),  _(some have already been removed eg. [cloudevent ](https://github.com/tektoncd/pipeline/pull/5995)and [cluster](https://github.com/tektoncd/pipeline/pull/5996) PipelineResources in v0.44)_, I think we might update the tag as `important soon`?

**Comment by piyush-garg** [comment]
it is done in the main branch and will be available with 0.31 release
