### ISSUE TITLE
Upgrading tkn With Brew Shows Incorrect tkn Version

### ISSUE THREAD

**Issue by danielhelfand** [tektoncd/cli#276]
# Expected Behavior

After running `brew upgrade tektoncd-cli` for the latest version of `tkn`, my expectation would be that running `tkn version` would return `Client version: 0.3.0`.

The change to the brew formula can be seen [here](https://github.com/chmouel/homebrew-tektoncd-cli/commit/eeef24dc20de616fc7ac264be75a731d6af2d01f). 

# Actual Behavior

`tkn version` returns `Client version: 6.6.6`

# Steps to Reproduce the Problem

1. Run `brew upgrade tektoncd-cli`
2. Run `tkn version`

**Comment by chmouel** [comment]
@danielhelfand this should be fixed now in https://github.com/chmouel/homebrew-tektoncd-cli/commit/7ed37a0e393bfd1ab2a1d421eff5b45b6aa6ebc4 feel free to `brew upgrade` and you should get the latest,

**Comment by danielhelfand** [comment]
`brew reinstall` worked and version is correct now. Thanks!

Any idea why the goreleaser bot picked up that version number for the auto update of the formula?

**Comment by chmouel** [comment]
I was testing a release fix https://github.com/tektoncd/cli/commit/93726c153d02ad026e710e3aada8612ac3d1ead1 that supposed to go only to my own repo (chmouel/tektoncd-cli)  but forgot that the token had right to my own github homebrew account, 

fun times as always 🎉 

(the bug is not fixed as well 😭 )

**Comment by danielhelfand** [comment]
@chmouel No worries! Thanks for the fix.
