### ISSUE TITLE
Add --last flag to tkn taskrun logs

### ISSUE THREAD

**Issue by navidshaikh** [tektoncd/cli#312]
# Expected Behavior
User should be able to stream logs for last taskrun in configured namespace, just like tkn has the flag for `pipeline logs`.

Enabling this flag would ease to not lookup the taskrun name each time I am creating a new taskrun and need to check its log, I'd simply do
```
tkn taskrun logs -l -f
```

**Comment by ImJasonH** [comment]
If the use case is "create a TaskRun then stream its logs", could we just build that into `tkn tr create`? It'd be great to have the default behavior block and stream logs, with an `--async` (naming TBD) option to not block.

I'm coming to this from my experience with `gcloud builds submit` which blocks while the build executes, so it can stream logs. If you `ctrl+C` during execution, it also cancels the Build, though sometimes users find that surprising. `gcloud builds submit` starts the Build without streaming logs, and `gcloud builds log <build-id>` picks up streaming logs for an ongoing/completedf build.

**Comment by chmouel** [comment]
@ImJasonH i agree this is a way better experience 99% of time users would want to look at the logs after starting it (unless it's run from a script so we would need a switch to disable that).

There is an issue for that here #274

**Comment by piyush-garg** [comment]
@navidshaikh I think you are asking about `tkn task logs -l -f` not taskrun according to the description you mentioned. Because a task has many taskruns and you can view the logs of the last run. Taskruns you can do by name, like pipelinerun. Pipeline has a `-l` feature but not pipelinerun.

In that case, we need to implement the `logs` command for `task`
