### ISSUE TITLE
UnExpected Behaviour of TaskRun cancel

### ISSUE THREAD

**Issue by praveen4g0** [tektoncd/cli#326]
# Expected Behavior
After Task Run, completed its execution and  when we try to cancel

./tkn tr cancel test-template-volume 
Expected std-err msg :  task run cannot be cancelled:  test-template-volume (It's already finished its execution)

# Actual Behavior

/tkn tr cancel test-template-volume
TaskRun cancelled: test-template-volume

# Steps to Reproduce the Problem

1. Create a task run in any namespace wait for its completion 
2.  ./tkn tr logs test-template-volume  -f

[read] some stuff
 
And 

./tkn tr list
NAME                   STARTED          DURATION     STATUS
test-template-volume   49 seconds ago   28 seconds   Succeeded

3. Now Try to perform tkn cancel operation

./tkn tr cancel test-template-volume
TaskRun cancelled: test-template-volume

./tkn tr list
NAME                   STARTED          DURATION     STATUS
test-template-volume   52 seconds ago   28 seconds   Succeeded

# Additional Info

**Comment by danielhelfand** [comment]
@praveen4g0 Thanks for reporting this! It looks as if the issue is that there is no check in the command as to whether the taskrun has succeeded or failed. It just [sets the status](https://github.com/tektoncd/cli/blob/1d1b7dcb98c5fd95c4959f2b9167a9e2c9b37377/pkg/cmd/taskrun/cancel.go#L66) of the taskrun to cancelled. There should be some type of validation in case the taskrun has a status other than running.
