### ISSUE TITLE
Feature Request: tkn pipeline version

### ISSUE THREAD

**Issue by praveen4g0** [tektoncd/cli#463]
# Expected Behavior
tkn pipeline version
pipeline version : v0.8.0
or 
tkn version
 Client version: 0.5.0
 Server version:  0.8.0
# Actual Behavior
N/A
or 
tkn version 
Client version: 0.5.0

# Additional Info

**Comment by vdemeester** [comment]
@praveen4g0 This is a tricky one, but two points

- It should be on `tkn version` instead of `tkn pipeline version`
- We don't have a way yet to return the version from the controller (without a huge hack). See tektoncd/pipeline#1543

Also, [`kn`](https://github.com/knative/client) is going to return the api version instead of the "knative release version". I think it might make more sense as it is what make the contract. But this is open to questions :angel: :wink:

**Comment by danielhelfand** [comment]
Dupe of #159. I'll close #159 though since a lot of the conversation is happening here.

**Comment by chmouel** [comment]
@waveywaves that one is a tricky one fyi, which involves some hard to tackle change in pipeline (to answer the question "what is the pipeline version" question)

**Comment by waveywaves** [comment]
Yes I was just checking that out. I was thinking something along the lines of https://github.com/kubernetes/kubernetes/tree/7f23a743e8c23ac6489340bbb34fa6f1d392db9d/staging/src/k8s.io/client-go/pkg/version in tektoncd/pipeline
