### ISSUE TITLE
Feature: `tkn task run` vs `tkn task start`

### ISSUE THREAD

**Issue by ImJasonH** [tektoncd/cli#524]
# Expected Behavior

I can "run" Tasks, not just "Start" them.

"Running" a Task results in a new "TaskRun" instance.

# Actual Behavior

In order to "run" a Task, I have to "Start" it.

When I "Start" a Task, it results in new "Task**Run**" instance.

# Additional Info

More concretely, I'd like to change the CLI to be able to call `tkn task run <task-name> --params...`, instead of `tkn task start ...`

If we decide to do this, we could support both for some amount of time, with a deprecation warning for `tkn task start`.

**Comment by bobcatfish** [comment]
![image](https://user-images.githubusercontent.com/432502/71027048-74a1b180-20d8-11ea-85a9-29279b141dd8.png)

**Comment by vdemeester** [comment]
btw, we can have both (aka `run` and `start`, one being an alias of the other, same way `docker run` and `docker container run` are aliases)

/kind question
/kind feature

**Comment by danielhelfand** [comment]
As of now, it looks like we support [trigger](https://github.com/tektoncd/cli/blob/master/pkg/cmd/task/start.go#L95) as an alias for pipeline start. It's obviously pretty well hidden as it's not promoted very well:

```
$ tkn pipeline start -h

Start pipelines

Usage:
tkn pipeline start pipeline [RESOURCES...] [PARAMS...] [SERVICEACCOUNT] [flags]

Aliases:
  start, trigger

Examples:
  
# start pipeline foo by creating a pipelinerun named "foo-run-xyz123" from the namespace "bar"
tkn pipeline start foo -s ServiceAccountName -n bar

For params value, if you want to provide multiple values, provide them comma separated
like cat,foo,bar


Flags:
  -h, --help                          help for start
  -l, --labels strings                pass labels as label=value.
  -L, --last                          re-run the pipeline using last pipelinerun values
  -p, --param stringArray             pass the param as key=value or key=value1,value2
  -r, --resource strings              pass the resource name and ref as name=ref
  -s, --serviceaccount string         pass the serviceaccount name
      --showlog                       show logs right after starting the pipeline (default true)
      --task-serviceaccount strings   pass the service account corresponding to the task

Global Flags:
  -c, --context string      name of the kubeconfig context to use (default: kubectl config current-context)
  -k, --kubeconfig string   kubectl config file (default: $HOME/.kube/config)
  -n, --namespace string    namespace to use (default: from $KUBECONFIG)
  -C, --nocolour            disable colouring (default: false)
```

I think I can agree to the idea of an alias, but it would make it hard to find. I am wondering if the basis of the issue has a lot to do with user experience? Are we seeing lots of people looking for run versus start?

**Comment by ImJasonH** [comment]
I think having a CLI verb `trigger` is going to get pretty confusing when/if `tkn` supports the `trigger` resource. 🤔 

I do like the idea of an alias though, but I'd still prefer to have `run` by the "main" way it's documented in examples. "Start" just isn't a term we use anywhere outside of the CLI.

**Comment by danielhelfand** [comment]
Yeah, removing `trigger` I think makes sense. To be candid, I wasn't aware it was an alias until now. I think it's feasible to switch to use run. I think it's worth it to raise this others on the CLI too, but I don't think it would be too painful. Especially since we could use the alias start to avoid deprecation.

**Comment by vdemeester** [comment]
> More concretely, I'd like to change the CLI to be able to call `tkn task run <task-name> --params...`, instead of `tkn task start ...`

The question is then, which one should be the "documented" one, `run` or `start` ?  and which one is the alias. If we just want to be able to do `tkn task run`, then, an alias is enough. If we want "to move to `run`" (aka `man tkn-task-run`, and highlighting `run` instead of `start` in documentation), then a change making `start` becamo `run` (with an alias like #526 would be better). We can also enhance our doc/manpage generator to generate aliases commands to (aka for `tkn foo` that have a bar alias, generating `tkn-foo` and `tkn-bar` as manpage and cli reference doc).

> If we decide to do this, we could support both for some amount of time, with a deprecation warning for `tkn task start`.

Definitely no deprecation ; with aliasing we can have those two *verbs* supported for ever.

**Comment by vdemeester** [comment]
> I think having a CLI verb `trigger` is going to get pretty confusing when/if `tkn` supports the `trigger` resource. :thinking: 

Right, I tend to agree it might be confusing — but it's more or less on the same lines as `run` then :angel:.

> I do like the idea of an alias though, but I'd still prefer to have `run` by the "main" way it's documented in examples. "Start" just isn't a term we use anywhere outside of the CLI.

On of the reason we went for `start` instead of `run` initially is that, you are effectively *starting* a task (or a pipeline) and then you watch the log — it was even more true before we had the `--showlog` defaulting to `true`. We can look at others:
- `kubectl` : when you want to have a `pod` running in your cluster, you `create` it ; you can `run` it but then it's an additionnal behaviour : it creates the deployment (or the podspec, …) and it attaches you to it. Both of those have there own commands : `kubectl create` and `kubectl exec`
- `docker`: this is even more "special", because you can `create` a container without executing it, and `start` or `stop` it independently. But if you want to `run` it, it actually does `create` + `start` + `attach` (optionally if you asked for being attached).

For me, `run` tends to give the impression that it's running under my control, that, if I kill my process (aka `CTRL-C`), the task will be cancelled for example, which will not the case if `start` and `run` are just aliases.

What I "wished" to have:
- have a `start` doesn't do `showlog` by default
- have a `run` that does `showlog` by default (and *does not* have an option to *disable* it), and handles signals (aka, I kill my process, my *run* is cancelled)

**Comment by ImJasonH** [comment]
@vdemeester Thanks for this feedback! I think I'm convinced. To summarize to make sure I've got it:

* `tkn task start` should start a TaskRun, print the new TaskRun name, then immediately exit. Users who want to stream logs can use that name to `tkn taskrun logs`, users who want to cancel can `tkn taskrun cancel`
* `tkn task run` should start a TaskRun, and begin streaming logs. Users who want to cancel can `ctrl+C`. This is basically the current behavior of `start`?
  * Perhaps `ctrl+C` should _prompt_ to cancel? How should we prompt while logs might continue to stream?

(For comparison, `gcloud builds submit` does this new `run` behavior, and `gcloud builds submit --async` does the new `start` behavior -- there isn't much usage of `--async`, but it fills a need for those that do use it.)

Does this sound okay to everyone? It seems like the difficult part will be staging the behavior change of `tkn task start` -- perhaps since it's still in `v0.x` we can just release this as a breaking change with a warning?

**Comment by vdemeester** [comment]
>     * `tkn task start` should start a TaskRun, print the new TaskRun name, then immediately exit. Users who want to stream logs can use that name to `tkn taskrun logs`, users who want to cancel can `tkn taskrun cancel`

Or could use a flag.

>     * `tkn task run` should start a TaskRun, and begin streaming logs. Users who want to cancel can `ctrl+C`. This is basically the current behavior of `start`?

This is not the current behaviour as if you terminated the `tkn task run`, we don't do anything for the `TaskRun` (no cancel) ; but yeah, this would be the behaviour I would like.

>       * Perhaps `ctrl+C` should _prompt_ to cancel? How should we prompt while logs might continue to stream?

ahah yeah, this is a good question :angel: 

> Does this sound okay to everyone? It seems like the difficult part will be staging the behavior change of `tkn task start` -- perhaps since it's still in `v0.x` we can just release this as a breaking change with a warning?

Right, we can definitely do some breakage as we are in `v0.x`, totally fine for me.

**Comment by sbwsg** [comment]
The `start` / `run` distinction sounds good to me and agree that a breaking change in 0.x is fine (... or at least better than waiting until after beta or 1.0 :smiling_imp: )

I'm less sure about ctrl+c cancelling the TaskRun. But this feels like something that could be added after `start` / `run`?  Another option could be an `--interactive` flag or similar for `run`?

**Comment by chmouel** [comment]
the changes are fine by me too 👍

better do the breaking change as early as possible.
