### ISSUE TITLE
Add a command for installing Tekton

### ISSUE THREAD

**Issue by siamaksade** [tektoncd/cli#61]
Installing Tekton Pipelines on a cluster can be simplified using the CLI:
```
tkn install
```

The command would configure the cluster (minikube, GCP, OpenShift, etc) and installs Tekton Pipelines.

**Comment by chmouel** [comment]
I think we should have a driver based install since there is multiple ways to do install, at least for openshift folks we want to advise to use the operator, i.e: https://github.com/vdemeester/home/blob/master/pkgs/scripts/bin/chos4#L41-L52 

as for others we want to use the released yaml file.....

do we really want to go down to the business of configuring a minikube or a OCP/GCP/AWS VMs ?

**Comment by danielhelfand** [comment]
> I think we should have a driver based install since there is multiple ways to do install, at least for openshift folks we want to advise to use the operator, i.e: https://github.com/vdemeester/home/blob/master/pkgs/scripts/bin/chos4#L41-L52
> 
> as for others we want to use the pipeline released yaml file.....

Agreed. We could also potentially support a version option that supports which version of pipelines to install, but we would have to remove certain version options for the CLI if there are breaking changes. Might be difficult to maintain.

> do we really want to go down to the business of configuring a minikube or a OCP/GCP/AWS VMs ?

I would say no. We should count on the user being able have to a cluster set up.

**Comment by siamaksade** [comment]
@chmouel agree on no need for VM setup. This was for just installing the YAML. I have doubts now on how useful this would be. It could be that simplifying installation of https://github.com/tektoncd/operator to a single `kubectl apply` would give the same result.

**Comment by vdemeester** [comment]
Closing this as it's a duplicate of #1472
