### ISSUE TITLE
UX: unify input/output and resources

### ISSUE THREAD

**Issue by ppitonak** [tektoncd/cli#732]
# Version and Operating System

**tkn Version:**
0.7.1

**Operating System:** 

all

# Expected Behavior

All `CRD`s and CLI use the same terminology

# Actual Behavior

`Task` and `ClusterTask` expect inputs and outputs but `Pipeline` and `Condition` expect resources. I need to think what flag to use although I'm doing something very similar.

`tkn ct start foo -i source=my-git-repo -o image=my-app-image`

vs

`tkn pipeline start foo -r source=my-git-repo -r image=my-app-image`

# Steps to Reproduce the Problem

1.
2.
3.

# Additional Info

**Comment by danielhelfand** [comment]
This is because Pipelines have [`Resources`](https://github.com/tektoncd/pipeline/blob/master/docs/pipelines.md#declared-resources) as part of the their specs, but Tasks have [Inputs](https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#inputs)/[Outputs](https://github.com/tektoncd/pipeline/blob/master/docs/tasks.md#outputs) under which resources are defined for their specs.

While I agree this is confusing at times, this is a result of how these resources were defined in the pipeline, and I think this is how this should remain moving forward. I think a bigger question is whether the distinction of input/output for tasks is really important, but I'm sure there's more to the design than I am accounting for. 

I am going to close this for now.
