### ISSUE TITLE
Enhance logs failure message in case of a task failing

### ISSUE THREAD

**Issue by vdemeester** [tektoncd/cli#83]
# Expected Behavior

When a Task fails, `tkn taskrun logs` (or `tkn pipelinerun logs`) should display something like `Step release has failed : some-error-message here`.

# Actual Behavior

It currently display : `failed to get logs for task release : container step-release has failed  : Error`

![2019-06-17-100207](https://user-images.githubusercontent.com/6508/59588683-774f2a00-90e8-11e9-8748-b27c1695c4ff.png)

/kind feature

**Comment by chmouel** [comment]
It is hard to know what failed, for example here : 

![image](https://user-images.githubusercontent.com/98980/66745724-19590600-ee80-11e9-9ef7-a753a70dc1bc.png)

what do we show instead of `Error`, showing last line would not get us anywhere,

I suggest that we just let it say that it failed and it's up to the user to read the log (that is already showing earlier in the log)
